add_newline = true
command_timeout = 200
format = "$os $username@$hostname\n${custom.gutter}[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[os]
disabled = false
format = "[$symbol]($style)"
style = "cyan"

[os.symbols]
Windows = ""
Arch = ""

[username]
disabled = false
show_always = true
format = "[$user]($style_user)"
style_user = "cyan"
style_root = "bold red"

[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"
style = "cyan"

[custom.gutter]
when = "true"
style = "cyan"
command = "Write-Host -NoNewline '╰─ '"
shell = ["powershell", "-NoProfile", "-Command"]
